FROM     node:14.18.2 as builder
WORKDIR  /app

ENV COODREAD_CONNSTR=""
ENV OTLP_ENDPOINT=""

RUN apt-get update && apt-get install telnet

COPY  package.json /app
COPY  nest-cli.json /app
COPY  tsconfig.build.json /app
COPY  tsconfig.json /app

COPY  src/ /app/src

EXPOSE   8082
CMD      ["tail", "-f", "/dev/null"]