# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: author.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='author.proto',
  package='GoodreadAuthor',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x61uthor.proto\x12\x0eGoodreadAuthor\"A\n\x06\x41uthor\x12\x11\n\tauthor_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0e\x61verage_rating\x18\x03 \x01(\x02\"2\n\x07\x41uthors\x12\'\n\x07\x61uthors\x18\x01 \x03(\x0b\x32\x16.GoodreadAuthor.Author\"+\n\x15GetAuthorByIdsRequest\x12\x12\n\nauthor_ids\x18\x01 \x03(\t2_\n\rAuthorService\x12N\n\nGetAuthors\x12%.GoodreadAuthor.GetAuthorByIdsRequest\x1a\x17.GoodreadAuthor.Authors\"\x00\x62\x06proto3'
)




_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='GoodreadAuthor.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='author_id', full_name='GoodreadAuthor.Author.author_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='GoodreadAuthor.Author.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='average_rating', full_name='GoodreadAuthor.Author.average_rating', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=97,
)


_AUTHORS = _descriptor.Descriptor(
  name='Authors',
  full_name='GoodreadAuthor.Authors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='authors', full_name='GoodreadAuthor.Authors.authors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=149,
)


_GETAUTHORBYIDSREQUEST = _descriptor.Descriptor(
  name='GetAuthorByIdsRequest',
  full_name='GoodreadAuthor.GetAuthorByIdsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='author_ids', full_name='GoodreadAuthor.GetAuthorByIdsRequest.author_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=194,
)

_AUTHORS.fields_by_name['authors'].message_type = _AUTHOR
DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
DESCRIPTOR.message_types_by_name['Authors'] = _AUTHORS
DESCRIPTOR.message_types_by_name['GetAuthorByIdsRequest'] = _GETAUTHORBYIDSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'author_pb2'
  # @@protoc_insertion_point(class_scope:GoodreadAuthor.Author)
  })
_sym_db.RegisterMessage(Author)

Authors = _reflection.GeneratedProtocolMessageType('Authors', (_message.Message,), {
  'DESCRIPTOR' : _AUTHORS,
  '__module__' : 'author_pb2'
  # @@protoc_insertion_point(class_scope:GoodreadAuthor.Authors)
  })
_sym_db.RegisterMessage(Authors)

GetAuthorByIdsRequest = _reflection.GeneratedProtocolMessageType('GetAuthorByIdsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETAUTHORBYIDSREQUEST,
  '__module__' : 'author_pb2'
  # @@protoc_insertion_point(class_scope:GoodreadAuthor.GetAuthorByIdsRequest)
  })
_sym_db.RegisterMessage(GetAuthorByIdsRequest)



_AUTHORSERVICE = _descriptor.ServiceDescriptor(
  name='AuthorService',
  full_name='GoodreadAuthor.AuthorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=196,
  serialized_end=291,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAuthors',
    full_name='GoodreadAuthor.AuthorService.GetAuthors',
    index=0,
    containing_service=None,
    input_type=_GETAUTHORBYIDSREQUEST,
    output_type=_AUTHORS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTHORSERVICE)

DESCRIPTOR.services_by_name['AuthorService'] = _AUTHORSERVICE

# @@protoc_insertion_point(module_scope)
