# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import book_pb2 as book__pb2


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBooks = channel.unary_unary(
                '/GoodreadBook.BookService/GetBooks',
                request_serializer=book__pb2.GetBookByIdsRequest.SerializeToString,
                response_deserializer=book__pb2.BookList.FromString,
                )
        self.GetBooksByAuthor = channel.unary_unary(
                '/GoodreadBook.BookService/GetBooksByAuthor',
                request_serializer=book__pb2.GetBookByAuthorIdsRequest.SerializeToString,
                response_deserializer=book__pb2.BookList.FromString,
                )


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksByAuthor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooks,
                    request_deserializer=book__pb2.GetBookByIdsRequest.FromString,
                    response_serializer=book__pb2.BookList.SerializeToString,
            ),
            'GetBooksByAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksByAuthor,
                    request_deserializer=book__pb2.GetBookByAuthorIdsRequest.FromString,
                    response_serializer=book__pb2.BookList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GoodreadBook.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GoodreadBook.BookService/GetBooks',
            book__pb2.GetBookByIdsRequest.SerializeToString,
            book__pb2.BookList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooksByAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GoodreadBook.BookService/GetBooksByAuthor',
            book__pb2.GetBookByAuthorIdsRequest.SerializeToString,
            book__pb2.BookList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
